### ISSUE TITLE
Pre-Flight Checklist

### ISSUE THREAD

**Issue by myles** [myles/mylesb.ca#3]
[57 Little Things to Double Check Before Your Website Launch](http://blog.hubspot.com/marketing/website-launch-checklist)

## Page Content

- [x] Web copywriting has been proofread. Spelling and grammar are correct.
- [x] Paragraphs, headers, lists, and other formatting are correct.
- [x] Copyright date (perhaps in the footer) includes the current year.
- [x] Company contact details are accurate throughout the website.
- [x] Generic content, such as lorem ipsum, has been properly removed and replaced.
- [x] Images are in the correct places, formatted and working on all devices.
- [x] Rights to images, fonts, and other content have been properly licensed and/or cited.

## Design

- [x] Website pages are compatible across browsers (IE 7 8, 9 and 10, Firefox, Chrome, Safari).
- [x] Website pages are compatible across devices (Android, iPhone, tablets).
- [x] CSS/HTML is properly validated.
- [x] Scripts are optimized across web pages.
- [x] Images are optimized across web pages.
- [x] CSS is optimized across web pages.
- [x] Favicon is in place and rendering properly.
- [x] Paragraph styles are working properly (headers, lists, block quotes).

## Functionality

- [x] Internal links across web pages are working properly.
- [x] External links across web pages are working properly, and open in a new tab.
- [x] Company logo is linked to the homepage.
- [x] Load time for site pages is optimized.

## SEO

- [x] Pages have unique page titles (fewer than 70 characters, includes keywords).
- [x] Pages have unique meta descriptions (fewer than 156 characters, includes keywords).
- [x] Pages have keywords (fewer than 10, all words appear in page copy).
- [x] Metadata is properly in place for any social media sharing content.
- [x] Spelling and grammar are correct in all metadata.
- [x] Alt tags have been added to every image.
- [x] A dynamic XML sitemap has been created.
- [x] The XML sitemap has been submitted to search engines.
- [x] Page URLs consistently reflect site information architecture.
- [x] 301 redirects are in place for all old URLs (redirecting old to new pages).
- [x] `rel="nofollow"` tags are in place on applicable links and pages.

## Analytics

- [x] Your website analytics codes have been inserted on website.
- [x] Relevant IP addresses have been excluded from analytics tracking.
- [x] Funnels and goals have been properly created in your analytics software (if applicable).
- [x] Google Webmaster and Google Analytics accounts have been properly synced.

## Security & Backups

- [x] 24/7 monitoring scripts are installed.
- [x] A copy of the final website has been made for backup purposes.
- [x] Ongoing copies of the website are being created and stored on a regular basis.

## Compliance

- [x] Web pages offer accessibility for users with disabilities (WAI-ARIA).
- [x] Website is compliant with usage rights for purchased or borrowed code, images, and fonts.
