### ISSUE TITLE
Pre-Flight Checklist

### ISSUE THREAD

**Issue by myles** [myles/mylesb.ca#6]
[57 Little Things to Double Check Before Your Website Launch](http://blog.hubspot.com/marketing/website-launch-checklist)

## Page Content

- [ ] Web copywriting has been proofread. Spelling and grammar are correct.
- [ ] Paragraphs, headers, lists, and other formatting are correct.
- [ ] Copyright date (perhaps in the footer) includes the current year.
- [ ] Company contact details are accurate throughout the website.
- [ ] Generic content, such as lorem ipsum, has been properly removed and replaced.
- [ ] Images are in the correct places, formatted and working on all devices.
- [ ] Videos are in the correct places, formatted and working on all devices.
- [ ] Audio files are in the correct places, formatted and working on all devices.
- [ ] All premium content, such as case studies, ebooks, and whitepapers, have been proofread. Spelling and grammar are correct.
- [ ] All premium content, such as case studies, ebooks, and whitepapers, are stored in their proper libraries/databases and work properly.
- [ ] Rights to images, fonts, and other content have been properly licensed and/or cited.

## Design

- [ ] Website pages are compatible across browsers (IE 7 8, 9 and 10, Firefox, Chrome, Safari).
- [ ] Website pages are compatible across devices (Android, iPhone, tablets).
- [ ] CSS/HTML is properly validated.
- [ ] Scripts are optimized across web pages.
- [ ] Images are optimized across web pages.
- [ ] CSS is optimized across web pages.
- [ ] Favicon is in place and rendering properly.
- [ ] Paragraph styles are working properly (headers, lists, block quotes).

## Functionality

- [ ] Forms are submitting data properly.
- [ ] Thank-you message or page displays after form is submitted.
- [ ] Form data is being emailed to a recipient and/or stored in a company database.
- [ ] Auto-responders are working properly (if applicable).
- [ ] Internal links across web pages are working properly.
- [ ] External links across web pages are working properly, and open in a new tab.
- [ ] Social media share icons are working properly.
- [ ] Feeds are working properly (RSS, news, social media).
- [ ] Company logo is linked to the homepage.
- [ ] Load time for site pages is optimized.
- [ ] 404 Redirect pages are in place (page-not-found.aspx).
- [ ] Integrations with third-party tools, such as your CRM, e-commerce software, and/or marketing platform, are running smoothly.

## SEO

- [ ] Pages have unique page titles (fewer than 70 characters, includes keywords).
- [ ] Pages have unique meta descriptions (fewer than 156 characters, includes keywords).
- [ ] Pages have keywords (fewer than 10, all words appear in page copy).
- [ ] Metadata is properly in place for any content in an RSS feed.
- [ ] Metadata is properly in place for any social media sharing content.
- [ ] Spelling and grammar are correct in all metadata.
- [ ] Alt tags have been added to every image.
- [ ] A dynamic XML sitemap has been created.
- [ ] The XML sitemap has been submitted to search engines.
- [ ] Page URLs consistently reflect site information architecture.
- [ ] 301 redirects are in place for all old URLs (redirecting old to new pages).
- [ ] `rel="nofollow"` tags are in place on applicable links and pages.

## Analytics

- [ ] Your website analytics codes have been inserted on website.
- [ ] Relevant IP addresses have been excluded from analytics tracking.
- [ ] Funnels and goals have been properly created in your analytics software (if applicable).
- [ ] Google Webmaster and Google Analytics accounts have been properly synced.
- [ ] Google AdWords and Google Analytics accounts have been properly synced (if applicable).

## Security & Backups

- [ ] 24/7 monitoring scripts are installed.
- [ ] A copy of the final website has been made for backup purposes.
- [ ] Ongoing copies of the website are being created and stored on a regular basis.
- [ ] Passwords and other website credentials are stored in a secure database.

## Compliance

- [ ] Web pages offer accessibility for users with disabilities (WAI-ARIA).
- [ ] Web pages announce if the website uses cookies (required in some countries).
- [ ] Website is compliant with usage rights for purchased or borrowed code, images, and fonts.
- [ ] Terms and privacy policies are visible to website visitors.
- [ ] Website is [PCI compliant](https://www.pcisecuritystandards.org/) (if you’re storing and processing credit cards).
